/*
 * @(#)Accounts.java
 *
 * Copyright 2024 by esoft systems (tm).
 * All rights reserved.
 */

package com.techvify.accounts.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Accounts.
 *
 * @author Daniel Tran - TVF
 * @since 1.0
 */

/*
 * The reason not using @Data instead of @Getter, @Setter, @ToString at the entities class because of don't want to generate equals and hashCode method.
 * Because sometimes equals and hashCode method is make the issues with the Spring data JPA framework.
 * But for Dto is ok so in Dto we can use @Data from lombok.
 * */
@Entity
@Table(name = "accounts")
@Getter
@Setter
@ToString
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class Accounts extends BaseEntity {

  @Column(name = "customer_id")
  private Long customerId;

  /*
   * The reason here only using @Id without any annotation related to automation generating the id.
   * Because of the account number (chinh la stk) should be a 10 digits number instead of a number start by 1,2,3... generated by the annotation
   * Following the common business of bank account.
   * */
  @Id
  @Column(name = "account_number")
  private String accountNumber;

  @Column(name = "account_type")
  private String accountType;

  @Column(name = "branch_address")
  private String branchAddress;
}
